@startuml
map "<<[StackFrame]>>" as _0f07b6f2a31cbd2e26428c51e8660b0dffe6e352 {
  fieldContainer =>
}
map "<<PrimitiveTypesDemo$FieldContainer>>" as _ea0aca3bedbad950e9d8b35c1bab07af352d76c4 {
  _boolean => false (boolean)
  _byte => 0 (byte)
  _char => \u0000 (char)
  _double => 0.000000 (double)
  _float => 0.000000 (float)
  _int => 0 (int)
  _long => 0 (long)
  _short => 0 (short)
}
_0f07b6f2a31cbd2e26428c51e8660b0dffe6e352::fieldContainer => _ea0aca3bedbad950e9d8b35c1bab07af352d76c4
@enduml
